### ISSUE TITLE
Chinese version of kanji

### ISSUE THREAD

**Issue by jayna37** [petlyh/JS-Dict#1]
Generally my Android device is set up correctly for Japanese, but both in the screenshots provided here in the repository as well as on my personal device, kanji are not rendered with their Japanese variant but instead look like Chinese.

Try out 曜 or 直 for some easy to discern examples.

**Comment by petlyh** [comment]
Thank you for bringing this to my attention. I see now that while kanji displays correctly on my personal device, it does not do so on other devices and on the emulator I used for the screenshots. I think I'll fix it by bundling a Japanese font in the app and either use it for all Japanese text or for the entire app.

**Comment by jayna37** [comment]
Interesting. I wonder why, on my device, kanji everywhere are displayed in Japanese variant but not in this app. I'm not experienced with Android but it's unlikely every single app I use has a bundled Japanese font I would guess.

**Comment by petlyh** [comment]
You are correct that most apps probably don't use a bundled font for this purpose. I believed it to be the only viable solution because of limitations of the Flutter framework that this app uses. However, it turns out that Flutter allows setting the locale used for rendering text, which can be used to fix this problem.
