### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [petlyh/JS-Dict#14]
https://gitlab.com/linsui/fdroiddata/-/jobs/7887028609

Could you please take a look? Thanks!

**Comment by petlyh** [comment]
Hi. Thanks for letting me know.

It looks like the commit in the build metadata is the latest commit on `main`, and not the commit that corresponds to the tag. Any idea why that might happen?

I'll have to look into why building that commit failed later, but that's not important for getting the current version on F-Droid, since the build error seem to be specific to the latest commit.

**Comment by linsui** [comment]
It failed with the same error so I updated the commit trying to fix it.

**Comment by petlyh** [comment]
I see. Both commits should be fixed now. It would be great if the commit in the build metadata could be changed back to `890587b` when it's re-enabled, so that the F-Droid and GitHub releases will match. Thanks!

Note to self: commits used in the forked flutter repo must be tagged so the flutter tool can tell what version the SDK is for dependency resolution.

**Comment by linsui** [comment]
Thanks!
