### ISSUE TITLE
Suggestions disappears in Mozc-based IMEs

### ISSUE THREAD

**Issue by jakob11git** [petlyh/JS-Dict#6]
Thanks for the fixes so far and the work. I have an issue with input into the search box. I do not know whether it is only related to JS-Dict application or has something to do with the Keyboard I'm using. However, I use many apps and I have only encountered this with JS-Dict on my system.

My keyboard: [OyaMozc](https://www.inworks.jp/download/oyamozc) ([Google Play](https://play.google.com/store/apps/details?id=jp.inworks.oyamozc&hl=ja))

Here's a video: https://github.com/petlyh/JS-Dict/assets/3247063/d6a1b221-1388-4a12-9c5d-46978720e067

As you can see, the prediction box opens and immediately closes again in most cases. I'm not sure why, but this happens so far only in this application for me.

**Comment by petlyh** [comment]
Never mind, I found an issue for it in the Flutter repository:
flutter/flutter#80218

**Comment by jayna37** [comment]
Thanks @petlyh for looking into this. So bug is upstream then :)

**Comment by petlyh** [comment]
Reopening this as I am now able to reproduce the issue and can attempt to fix it in Flutter.

**Comment by petlyh** [comment]
I've now found the code that causes the bug. Since I'm not that familiar with Flutter framework development, I'm not sure what a proper upstream fix would look like (and it would take a while for it to get into a release anyway), so for now I've just patched it out in my fork which I'll use to build JS-Dict.
